-- local bufferline = require('bufferline')
-- bufferline.setup {
--     options = {
--         style_preset = bufferline.style_preset.minimal,
--         diagnostics = "nvim_lsp",
--         offsets = {
--             filetype = "NvimTree"
--         }
--     }
-- }
--
--
--
